desc "Builds"
lane :build_for_testing do
  scan(clean: true,
       workspace: "TinkoffChat.xcworkspace",
       scheme: "TinkoffChat",
       build_for_testing: true)

  puts "Builds done!"
end

desc "Run tests"
lane :run_tests do
  scan(device: "iPhone 11",
       workspace: "TinkoffChat.xcworkspace",
       scheme: "TinkoffChat",
       testplan: "UnitTests",
       skip_build: true)

  puts "Tests done!"
end

desc "Build and run tests"
lane :build_and_test do
  build_for_testing
  run_tests

  puts "Build and run tests done!"
end