name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Build and run tests
      run: bundle exec fastlane build_and_test
